#
# Implementation of Continuous Integration process for macOS 13 by Github actions (with extra additionals...)
#
name: "CI (macOS 13)"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  # CI on macOS/x86_64
  ci-macos13-qt6:
    name: "macOS (x86_64; qt6)"
    runs-on: macos-13
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.actor, 'transifex')"

    # @TODO Enable gpsd on macOS instance for CI testing
    # @BODY At the moment after installing gpsd (brew install gpsd) library can be found by cmake, but not headers! Apparently we should add some magic for environment variables or something else on macOS Catalina to make headers available for cmake/make
    steps:
    - name: Install dependencies
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        brew update
        brew install qt@6 nlopt exiv2

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      shell: bash
      run: |
        export PATH="/usr/local/opt/qt@6/bin:$PATH"
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=On ${{ github.workspace }}

    - name: Compile
      working-directory: build
      run: make -j3

    - name: Run unit tests
      uses: coactions/setup-xvfb@v1
      with:
        working-directory: build
        run: ctest --output-on-failure

  # CI on macOS/arm64 
  ci-macos13arm:
    name: "macOS (arm64; qt6)"
    runs-on: macos-13-arm64
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.actor, 'transifex')"

    # @TODO Enable gpsd on macOS instance for CI testing
    # @BODY At the moment after installing gpsd (brew install gpsd) library can be found by cmake, but not headers! Apparently we should add some magic for environment variables or something else on macOS Catalina to make headers available for cmake/make
    steps:
    - name: Install dependencies
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        brew update
        brew install qt@6 nlopt exiv2

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      shell: bash
      run: |
        export PATH="/usr/local/opt/qt@6/bin:$PATH"
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=On ${{ github.workspace }}

    - name: Compile
      working-directory: build
      run: make -j3

    - name: Run unit tests
      uses: coactions/setup-xvfb@v1
      with:
        working-directory: build
        run: ctest --output-on-failure
